refactor(mem): move ui target
Also add a workaround for for type crossing DLL boundaries.
Error: Cannot assign QObject* to ARawMemory*

WILL NOT SHOW MEMRY DUMP DUE TO BUG.

# BUG: Can't be STATIC, otherwise Qt meta objects for raw memory get linked into program many times.
# This causes qobject_cast<ARawMemory*> to fail.