build: fix intermittent changelogdb generation error on Windows
Usually fails with:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\shutil.py", line 847, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp8b2_xgyn/temp.db' -> 'D:/a/Pepp/Pepp/build/changelog.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\Pepp\Pepp\scripts\changelog_tools.py", line 234, in <module>
    if hasattr(args, 'func'): args.func(args)
                              ^^^^^^^^^^^^^^^
  File "D:\a\Pepp\Pepp\scripts\changelog_tools.py", line 150, in to_sqlite
    shutil.move(newdir+"/temp.db", args.db)
  File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\shutil.py", line 867, in move
    copy_function(src, real_dst)
  File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
```